version: '3.8'

services:
  nestjs:
    container_name: nestjs-dev
    build:
      context: backend
      target: development
      dockerfile: Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - ./backend/app:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
    nesjs-network: