#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $DB_USERNAME WITH PASSWORD '$DB_PASSWORD';
	CREATE DATABASE $DB_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USERNAME;
	GRANT ALL ON DATABASE $DB_NAME TO $DB_USERNAME;
	GRANT USAGE, CREATE ON SCHEMA PUBLIC TO $DB_USERNAME;
	ALTER DATABASE $DB_NAME OWNER TO $DB_USERNAME;

EOSQL
