name: Docker Image CI
on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: echo "Build a backend container image"
        run: docker compose -f docker-compose.yml build backend
  build-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: echo "Build a backend container image"
        run: docker compose -f docker-compose.yml build database
    env:
      DB_NAME: ft_trancendence
      DB_USERNAME: githubaction
      DB_PASSWORD: 424242
