name: Docker Image CI
on: push

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: debug list
        run: |
          pwd
          ls -l
      - name: echo "Build a backend container image"
        run: docker compose -f docker-compose.yml build backend
    env:
      DB_NAME: ft_trancendence
      DB_USERNAME: githubaction
      DB_PASSWORD: 424242
  build-database:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build a frontend container image"

