name: Docker Image CI
on: push

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build a backend container image"
  build-database:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build a frontend container image"